-- IMAGE MODELS (columns are jsonb)
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3"]'::jsonb, supported_resolutions = '["1K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'nano-banana-2';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3","21:9"]'::jsonb, supported_resolutions = '["1K","2K","4K"]'::jsonb, default_aspect = '1:1', default_resolution = '2K' WHERE slug = 'nano-banana-pro';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","2:3","3:2"]'::jsonb, supported_resolutions = '["1K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'gpt-image-2';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3","21:9"]'::jsonb, supported_resolutions = '["1K","2K","4K"]'::jsonb, default_aspect = '1:1', default_resolution = '2K' WHERE slug = 'seedream-4-5';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3","21:9"]'::jsonb, supported_resolutions = '["1K","2K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'flux-2-pro';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3"]'::jsonb, supported_resolutions = '["1K","2K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'flux-kontext-pro';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3","16:10","10:16"]'::jsonb, supported_resolutions = '["1K","2K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'ideogram-3';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3","21:9"]'::jsonb, supported_resolutions = '["1K","2K"]'::jsonb, default_aspect = '16:9', default_resolution = '2K' WHERE slug = 'lucid-origin';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3"]'::jsonb, supported_resolutions = '["1K","2K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'phoenix-1';
UPDATE public.fal_image_models SET supported_aspects = '["1:1","16:9","9:16","4:3","3:4","3:2","2:3"]'::jsonb, supported_resolutions = '["1K"]'::jsonb, default_aspect = '1:1', default_resolution = '1K' WHERE slug = 'flux-dev';

-- VIDEO MODELS
UPDATE public.fal_video_models SET supported_aspects = '["16:9","9:16","1:1"]'::jsonb, supported_resolutions = '["720p","1080p"]'::jsonb, supported_durations = '[4,6,8]'::jsonb, default_aspect = '16:9', default_resolution = '1080p', default_duration = 8, supports_audio = true WHERE slug = 'veo-3-1';
UPDATE public.fal_video_models SET supported_aspects = '["16:9","9:16","1:1"]'::jsonb, supported_resolutions = '["720p","1080p"]'::jsonb, supported_durations = '[5,10]'::jsonb, default_aspect = '16:9', default_resolution = '1080p', default_duration = 5, supports_audio = true WHERE slug = 'kling-3-0';
UPDATE public.fal_video_models SET supported_aspects = '["16:9","9:16","1:1"]'::jsonb, supported_resolutions = '["720p","1080p"]'::jsonb, supported_durations = '[5,10]'::jsonb, default_aspect = '16:9', default_resolution = '1080p', default_duration = 5, supports_audio = false WHERE slug = 'seedance-2-0';
UPDATE public.fal_video_models SET supported_aspects = '["16:9","9:16","1:1"]'::jsonb, supported_resolutions = '["720p","1080p"]'::jsonb, supported_durations = '[5,10]'::jsonb, default_aspect = '16:9', default_resolution = '720p', default_duration = 5, supports_audio = false WHERE slug = 'seedance-2-0-fast';
UPDATE public.fal_video_models SET supported_aspects = '["16:9","9:16","1:1"]'::jsonb, supported_resolutions = '["720p","1080p"]'::jsonb, supported_durations = '[6,10]'::jsonb, default_aspect = '16:9', default_resolution = '1080p', default_duration = 6, supports_audio = false WHERE slug = 'hailuo-2-3';
UPDATE public.fal_video_models SET supported_aspects = '["16:9","9:16","1:1"]'::jsonb, supported_resolutions = '["720p","1080p"]'::jsonb, supported_durations = '[5,8]'::jsonb, default_aspect = '16:9', default_resolution = '1080p', default_duration = 8, supports_audio = true WHERE slug = 'ltx-2-3-pro';